spring:
  application:
    name: Hotel
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    csrf:
      enabled: true